import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainMenu from "./main-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-[1440px] mx-auto mt-8">
          <MainMenu />
          <main className="mt-9">{children}</main>
        </div>
        <footer className=" text-slate-700 flex justify-center items-center my-12">
          Lance Liang &copy; {new Date().getFullYear().toString()} | All rights
          reserved
        </footer>
      </body>
    </html>
  );
}
